### PR TITLE
Added Duckdns and LetsEncypt

### PR DESCRIPTION
**Pull request by agusalex**

### CODE REVIEW

**Comment by iHiD** [comment]
@agusalex Are you wanting to add a prog2 track?

**Comment by agusalex** [comment]
Hey! Sorry, I was testing stuff and mistakenly created a PR for your repo instead of the fork.

**Comment by agusalex** [comment]
We are setting things up so that we have a python algorithms course for the university we teach at and Excercism is just perfect for us.

**Comment by iHiD** [comment]
Nice :) Shout if you'd like to discuss anything.

**Pull request closed without merging**
