### PR TITLE
Add bundle install

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by iHiD** [comment]
Sweet - thanks!

**Comment by joshgoebel** [comment]
What is in the bundle that needs to be installed?

**Comment by ErikSchierboom** [comment]
Some aws gem

**Comment by iHiD** [comment]
@joshgoebel It's the [Gemfile](https://github.com/exercism/development-environment/blob/master/Gemfile#L8) of the project, which at least requires [ActiveSupport](https://github.com/exercism/development-environment/blob/master/lib/docker_compose.rb#L4-L6).

We can stripe most of this into groups as we previously discussed, but we'll still need active support etc unless you want to rewrite those bits without it.

**Comment by joshgoebel** [comment]
Oh, hahaha, forgot I used AS. :-)  I just hated to use strings everywhere... and eventually we may need another Gem for something, so I guess this is fine.

**Pull request merged**
